name: 'Common Setup'
description: 'Set up JDK and grant execute permissions for gradlew'

inputs:
  java-version:
    description: 'Java version'
    required: true
    default: '21'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'zulu'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
