name: 'Common Setup'
description: 'Set up the JDK and Gradle'

inputs:
  java-version:
    description: 'Java version'
    required: true
    default: '25'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'microsoft'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
