name: Build and Draft Release

on:
  push:
    tags:
      - 'v*' # For v1.0, v0.1.0, etc

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew -Pver=${GITHUB_REF/refs\/tags\//} release

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Compiled Jar(s)
          path: ${{ github.workspace }}/build/libs/

      - name: Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          body: |
            # Recent Changes

            ## Improvements 🏗️
            * Item 1

            ## Bug Fixes 🐞
            * Item 2

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/build/libs/ExamplePlugin.jar
          asset_name: ExamplePlugin.jar
          asset_content_type: application/java-archive
